apiVersion: wso2.com/v1alpha1
kind: TargetEndpoint
metadata:
  name: products
  namespace: micro
  labels:
    app: products
spec:
  protocol: http
  port: 80
  targetPort: 9090
  deploy:
    name: products
    dockerImage: pubudu/products:1.0.0
    count: 1

---
apiVersion: wso2.com/v1alpha1
kind: TargetEndpoint
metadata:
  name: inventory
  namespace: micro
  labels:
    app: inventory
spec:
  protocol: http
  port: 80
  targetPort: 80
  deploy:
    name: inventory
    dockerImage: pubudu/inventory:1.0.0
    count: 1

---
apiVersion: wso2.com/v1alpha1
kind: TargetEndpoint
metadata:
  name: review
  namespace: micro
  labels:
    app: review
spec:
  protocol: http
  port: 80
  targetPort: 8080
  deploy:
    name: review
    dockerImage: pubudu/review:1.0.0
    count: 1